Add openshift-pipelines fips assessment task(s)
opdev/fips-assessments pull request #20
Opened 2023-08-04 15:27 UTC by mrhillsman

Resolves #16

2023-08-14 13:02 UTC, bcrochet requested changes
Couple of requests, but overall looking good.

2023-08-14 20:36 UTC, mrhillsman commented on openshift-pipelines/tasks/main.yml
> +                  storage: 500Mi
Yes

2023-08-14 20:36 UTC, mrhillsman commented on openshift-pipelines/tasks/main.yml
> +- name: Check if ServiceAccount pipeline exists in pipelines-tutorial namespace
Done

2023-08-14 20:36 UTC, mrhillsman commented on openshift-pipelines/tasks/main.yml
> +                  storage: 500Mi
Done

2023-08-16 15:17 UTC, bcrochet reviewed
Just a question about the definitions.

2023-08-16 23:25 UTC, mrhillsman commented
Just leaving a note that I've see the pipelinerun fail due to not pulling down GitHub repo so need to do some refactoring for the pipelineruns at a minimum.

2023-08-17 15:43 UTC, bcrochet requested changes
Just a couple of comments.

2023-08-17 15:43 UTC, bcrochet commented on openshift-pipelines/tasks/main.yml
> +
Looks like this still needs to report the result back?

2023-08-17 15:43 UTC, bcrochet commented on openshift-pipelines/tasks/main.yml
> +    wait_condition:
This isn't strictly necessary. For state: absent, and wait: true it automatically does the right thing, and waits until it is actually deleted.

2023-08-22 18:33 UTC, bcrochet approved these changes
/lgtm

2023-08-22 18:34 UTC, merged