Create Ansible task to install devspace operator cr
opdev/fips-assessments pull request #36
Opened 2023-08-16 17:13 UTC by rocrisp

#28

2023-08-16 17:46 UTC, rocrisp commented
I need to add a task to clean up the operand.

2023-08-16 19:03 UTC, bcrochet requested changes
See comment

2023-08-16 19:38 UTC, rocrisp commented on devspaces/tasks/main.yml
> +        test_result: "failed"
Hmm, upon checking, Matt uses "failed". See -> https://github.com/opdev/fips-assessments/blob/main/datagrid/tasks/main.yml#L141

2023-08-16 19:39 UTC, rocrisp commented on devspaces/tasks/main.yml
> +        test_result: "failed"
Let me know what you guys decide

2023-08-16 20:24 UTC, rocrisp commented on devspaces/tasks/main.yml
> +        test_result: "failed"
I just saw the final verdict from failed to fail

2023-08-16 20:52 UTC, rocrisp commented on devspaces/tasks/main.yml
> +        test_result: "failed"
I made the change from failed to fail.

2023-08-17 11:46 UTC, bcrochet requested changes
A few comments and suggestions. Otherwise, looks good!

2023-08-17 11:46 UTC, bcrochet commented on devspaces/tasks/main.yml
> +    test_result: "pass"
```suggestion
    assessment_result: "pass"
```

2023-08-17 11:46 UTC, bcrochet commented on devspaces/tasks/main.yml
> +        - "'status' in checluster_info.resources[0]"
```suggestion
        - checluster_info.resources[0].status is defined
```

2023-08-17 11:46 UTC, bcrochet commented on devspaces/tasks/main.yml
> +        - "'chePhase' in checluster_info.resources[0].status"
```suggestion
        - checluster_info.resources[0].status.chePhase is defined"
```

2023-08-17 11:46 UTC, bcrochet commented on devspaces/tasks/main.yml
> +        - checluster_info.resources[0].status.chePhase == "Active"
I like how you grouped these!

2023-08-17 11:46 UTC, bcrochet commented on devspaces/tasks/main.yml
> +        test_result: "fail"
```suggestion
        assessment_result: "fail"
```

2023-08-17 11:46 UTC, bcrochet commented on devspaces/tasks/main.yml
> +- name: Create result
If you change the above you can get rid of this task.

2023-08-17 11:46 UTC, bcrochet commented on devspaces/tasks/main.yml
> +        test_result: "fail"
I don't think you want to fail on cleanup. I'd remove this task.

2023-08-17 11:46 UTC, bcrochet commented on devspaces/tasks/main.yml
> +    msg: "{% if test_result == 'pass' %} PASS {% else %} FAILED {% endif %}"
```suggestion
    msg: "{% if assessment_result == 'pass' %} PASS {% else %} FAIL {% endif %}"
```
Alternatively (which is a little more idiomatic Ansible):

```suggestion
    msg: "{{ (assessment_result == 'pass') | ternary('PASS', 'FAIL') }}"
```

2023-08-19 12:47 UTC, bcrochet requested changes
Please squash to a single commit.

2023-08-21 16:53 UTC, rocrisp commented on devspaces/tasks/main.yml
> +        - checluster_info.resources[0].status.chePhase == "Active"
Thanks

2023-08-21 20:16 UTC, bcrochet requested changes
Just one more fix, collapse back to 1 commit, and this looks ready. Thanks!

2023-08-21 20:16 UTC, bcrochet commented on devspaces/tasks/main.yml
> +    msg: "{% if assessment_result == 'pass' %} PASS {% else %} FAIL {% endif %}"
File should have a trailing newline here.

2023-08-22 16:05 UTC, bcrochet approved these changes
/lgtm

2023-08-22 16:06 UTC, merged